// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAW9OSSrpzdCwA2jxk6EglrFnWfspltoXM',
    appId: '1:950613080047:web:c2b2af1e729e31d20ce81a',
    messagingSenderId: '950613080047',
    projectId: 'order--menu',
    authDomain: 'order--menu.firebaseapp.com',
    storageBucket: 'order--menu.firebasestorage.app',
    measurementId: 'G-M0SEQ5FSLV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCc7aWY3K8vjLd2GAxsx1q9BSK3Tt0T7rw',
    appId: '1:950613080047:android:a43881fa7a6c25660ce81a',
    messagingSenderId: '950613080047',
    projectId: 'order--menu',
    storageBucket: 'order--menu.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCuuy1s-VZikj5boczqnw9wcEPJG79BVjE',
    appId: '1:950613080047:ios:a841c6a5669daa040ce81a',
    messagingSenderId: '950613080047',
    projectId: 'order--menu',
    storageBucket: 'order--menu.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCuuy1s-VZikj5boczqnw9wcEPJG79BVjE',
    appId: '1:950613080047:ios:a841c6a5669daa040ce81a',
    messagingSenderId: '950613080047',
    projectId: 'order--menu',
    storageBucket: 'order--menu.firebasestorage.app',
    iosBundleId: 'com.example.untitled1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAW9OSSrpzdCwA2jxk6EglrFnWfspltoXM',
    appId: '1:950613080047:web:eaf66bca5299db320ce81a',
    messagingSenderId: '950613080047',
    projectId: 'order--menu',
    authDomain: 'order--menu.firebaseapp.com',
    storageBucket: 'order--menu.firebasestorage.app',
    measurementId: 'G-6SB3D80WRM',
  );
}